server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${secrets.PROD_DB_HOST}:${secrets.PROD_DB_PORT}/${secrets.PROD_DB_NAME}?sslmode=require&ssl=true
    username: ${secrets.PROD_DB_USERNAME}
    password: ${secrets.PROD_DB_PASSWORD}

logging:
  level:
    root: WARN
